### ISSUE TITLE
Glyph text issue

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [GlobalQuran/mobile-app#25]
@iBasit are we using the correct glyph (text) to render the Arabic text, I just noticed that there is extra meem's on Surah 2 ayah 19, on Tanzil it's not being displayed even when using the same font Scheherazade. 
![image](https://cloud.githubusercontent.com/assets/7900956/14232690/531ed24e-f9aa-11e5-958e-d4c98a27b20f.png)

**Comment by Ashraf-Ali-aa** [comment]
not sure what has changed but I could not reproduce the issue on http://globalquran.com/en.transliteration+quran-uthmani/2:19

**Comment by iBasit** [comment]
Let  me know if you are still viewing this issue, as I don't see it.

![image](https://cloud.githubusercontent.com/assets/34341/14582897/7fb9403c-0409-11e6-9e9d-e6da6a8af6ac.png)

**Comment by Ashraf-Ali-aa** [comment]
@basit from your screenshot I can still see it but it's overlaping with the text so it's a bit more difficult to see it.
