### ISSUE TITLE
bug building the app

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [GlobalQuran/mobile-app#31]
When you try to run the command `ionic serve` the build fails

```
$ ionic serve
error:
Github/Personal/mobile-app/node_modules/ng2-vs-for/src/ng2-vs-for.ts:1
import {
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
^C
```

**Comment by Ashraf-Ali-aa** [comment]
@iBasit I think we can use this from ionic http://ionicframework.com/docs/v2/api/components/virtual-scroll/VirtualScroll/

**Comment by iBasit** [comment]
this will cause issue with approxItemHeight, it was same with vs-for too or any other virtual scroll.  since we don't know or cant calculate exact height for each row and all rows have different heights.
